// Frozen architecture manifest. Single source of truth for the OS surface.
import type { ArchitectureManifest } from "./types";

export const ARCHITECTURE: ArchitectureManifest = {
  primitives: [
    {
      id: 1,
      name: "Package",
      role: "Everything that exists in a World is a Package — assets, systems, sensory devices, renderers.",
      frozen: true,
    },
    {
      id: 2,
      name: "Specification",
      role: "Canonical truth. Distinct from NL, prompt, and generated artifact.",
      frozen: true,
    },
    {
      id: 3,
      name: "Contract",
      role: "Capability families. Packages provide/require. The Composer wires them. The Kernel enforces them.",
      frozen: true,
    },
    {
      id: 4,
      name: "Entity",
      role: "A Package instantiated into a running World.",
      frozen: true,
    },
    {
      id: 5,
      name: "World Project",
      role: "Git-like collaborative source repository for a World. Contributions are packages, not code.",
      frozen: true,
    },
    {
      id: 6,
      name: "World Build",
      role: "Immutable, reproducible composition artifact.",
      frozen: true,
    },
    {
      id: 7,
      name: "Kernel",
      role: "Scheduler, Event Bus, Entity Runtime, Capability System, Networking, Replication, Spatial Authority, Persistence, Streaming — OS substrate, never LLM-generated.",
      frozen: true,
    },
    {
      id: 8,
      name: "Runtime Adapter",
      role: "Boundary so browser/WASM/native/VR/AR/cloud can all implement the same contract.",
      frozen: true,
    },
    {
      id: 9,
      name: "World Node",
      role: "Deployable multiplayer runtime instance of a Build. Host is an implementation detail.",
      frozen: true,
    },
    {
      id: 10,
      name: "World Service",
      role: "Platform-provided OS services: Multiplayer, Streaming, Persistence, Voice, Ads, Identity... Packages consume them through Contracts — never reinvent them.",
      frozen: true,
    },
  ],
  pipelines: [
    {
      name: "Generation (reuse-first)",
      stages: [
        "Natural Language",
        "World Specification",
        "Package Decomposition",
        "Registry Search",
        "Reuse Existing / Generate Missing",
        "User's LLM (only for missing)",
        "Certified Packages",
        "Composition",
        "World Build",
        "World Node",
        "Living World (multiplayer + streaming + persistence)",
      ],
    },
    {
      name: "Multimodal",
      stages: [
        "Photo / Video / Audio / Scan",
        "Perception → World Specification",
        "…same reuse-first pipeline…",
      ],
    },
  ],
  laws: [
    "No future feature may introduce a fundamental object that bypasses Package, Specification, Contract, Entity, World Project, World Build, Kernel, Runtime Adapter, World Node, or World Service.",
    "The user's LLM implements PACKAGES against OS contracts. It NEVER implements OS substrate (multiplayer, networking, replication, streaming, persistence, capability enforcement, platform services).",
    "No future feature should require PlayLiquid to own the user's implementation model, LLM, or hosting infrastructure.",
    "A package must remain reusable across worlds. Worlds layer capability policies on top — they do not modify packages. (Superman can fly in 500 worlds and be grounded in 501 without 501 implementations.)",
  ],
  // The critical OS-substrate-vs-LLM-implementation distinction
  substrate: {
    osProvides: [
      "Specification system",
      "Package Registry",
      "Dependency resolution",
      "Composition",
      "World builds",
      "Entity lifecycle",
      "Scheduler",
      "Event bus",
      "Networking",
      "Multiplayer / Replication",
      "Spatial partitioning",
      "Streaming",
      "Persistence",
      "Capability enforcement (multi-layer)",
      "Asset delivery",
      "World hosting (World Nodes)",
      "Observability",
      "Moderation hooks",
      "Platform services (Identity, Voice, Ads, Economy...)",
    ],
    llmImplements: [
      "Castles, houses, roads, trees",
      "Avatars, creatures, NPCs, vehicles",
      "Weather systems, economies, quest systems",
      "Museums, schools, Mars rovers, spaceships",
      "World-specific visual style, architecture, materials",
      "Domain logic that consumes OS contracts",
    ],
  },
  kernelServices: [
    { name: "Scheduler", contract: "kernel.scheduler", role: "Advances simulation ticks; orders entity updates." },
    { name: "Event Bus", contract: "kernel.events", role: "Pub/sub for entity and system events." },
    { name: "Entity Runtime", contract: "kernel.entities", role: "Spawns, updates, despawns entities from packages." },
    { name: "Capability System", contract: "kernel.capabilities", role: "Multi-layer negotiation: entity × world × zone × experience = effective." },
    { name: "Networking", contract: "kernel.networking", role: "Transport abstraction. Packages never implement transport." },
    { name: "Replication", contract: "kernel.replication", role: "Authoritative state → interested clients. Automatic for all packages." },
    { name: "Session Management", contract: "kernel.sessions", role: "Player connections, presence, reconnect." },
    { name: "Spatial Authority", contract: "kernel.spatial", role: "Cells, regions, interest management, streaming partitions." },
    { name: "Persistence", contract: "kernel.persistence", role: "World/entity state survives restart. Adapter-based (Postgres/IPFS/local)." },
    { name: "Streaming", contract: "kernel.streaming", role: "Loads/unloads spatial cells based on player interest. Packages declare bounds + LOD." },
  ],
  extensionTable: [
    { capability: "Multiplayer", extensionPoint: "Kernel / Replication + Sessions (OS substrate, NOT LLM)" },
    { capability: "Dedicated servers", extensionPoint: "World Node" },
    { capability: "P2P worlds", extensionPoint: "World Node" },
    { capability: "Streaming", extensionPoint: "Kernel / Spatial Authority (OS substrate)" },
    { capability: "Persistence", extensionPoint: "Kernel / Persistence Adapter (OS substrate)" },
    { capability: "Avatars", extensionPoint: "Package + Entity + Capability Policy" },
    { capability: "Capability restrictions", extensionPoint: "Kernel / Multi-layer Capability Negotiation" },
    { capability: "Physics", extensionPoint: "Runtime Adapter / Package" },
    { capability: "Rendering", extensionPoint: "Runtime Adapter" },
    { capability: "VR / AR", extensionPoint: "Runtime Adapter" },
    { capability: "Audio", extensionPoint: "Package + Runtime Service" },
    { capability: "Voice", extensionPoint: "World Service (OS substrate)" },
    { capability: "Smell / Haptics", extensionPoint: "Sensory Package + Runtime Adapter" },
    { capability: "Advertising", extensionPoint: "World Service (OS substrate) — never LLM-generated" },
    { capability: "Economy", extensionPoint: "World Service (OS substrate)" },
    { capability: "AI agents", extensionPoint: "Entity + Knowledge/AI Package" },
    { capability: "Real-world reconstruction", extensionPoint: "Multimodal → Specification" },
    { capability: "New LLM providers", extensionPoint: "Provider Adapter" },
    { capability: "New hosting providers", extensionPoint: "World Node Adapter" },
    { capability: "New execution technology", extensionPoint: "Runtime Adapter" },
  ],
  roadmap: [
    { stage: "0", name: "Freeze the Kernel Contract", status: "done", detail: "10 primitives, capability model, event model, spatial model, service contracts." },
    { stage: "1", name: "Make the Package Ecosystem Real", status: "in-progress", detail: "Registry search, reuse-first generation, theme compatibility, fork/variation." },
    { stage: "2", name: "World Projects as GitHub for Worlds", status: "in-progress", detail: "Contributions, spatial slots, package ownership, immutable builds." },
    { stage: "3", name: "Make the Kernel Actually Multiplayer", status: "partial", detail: "Sessions, replication, interest management, spatial partitioning, streaming — as OS substrate." },
    { stage: "4", name: "Universal World Runtime", status: "partial", detail: "World Node as real deployable multiplayer runtime." },
    { stage: "5", name: "Platform Services", status: "partial", detail: "Identity, Multiplayer, Persistence, Streaming, Voice, Ads, Economy — each a stable Contract." },
    { stage: "6", name: "Multimodal World Reconstruction", status: "planned", detail: "Photo/video/audio → perception → world specification → reuse-first pipeline." },
  ],
};
