// Frozen architecture manifest. Single source of truth for the OS surface.
import type { ArchitectureManifest } from "./types";

export const ARCHITECTURE: ArchitectureManifest = {
  primitives: [
    {
      id: 1,
      name: "Package",
      role: "Everything that exists in a World is a Package — assets, systems, sensory devices, renderers.",
      frozen: true,
    },
    {
      id: 2,
      name: "Specification",
      role: "Canonical truth. Distinct from NL, prompt, and generated artifact.",
      frozen: true,
    },
    {
      id: 3,
      name: "Contract",
      role: "Capability families. Packages provide/require. The Composer wires them. The Kernel enforces them.",
      frozen: true,
    },
    {
      id: 4,
      name: "Entity",
      role: "A Package instantiated into a running World.",
      frozen: true,
    },
    {
      id: 5,
      name: "World Project",
      role: "Git-like collaborative source repository for a World. Contributions are packages, not code.",
      frozen: true,
    },
    {
      id: 6,
      name: "World Build",
      role: "Immutable, reproducible composition artifact.",
      frozen: true,
    },
    {
      id: 7,
      name: "Kernel",
      role: "Scheduler, Event Bus, Entity Runtime, Capability System, Networking, Replication, Spatial Authority, Persistence, Streaming — OS substrate, never LLM-generated.",
      frozen: true,
    },
    {
      id: 8,
      name: "Runtime Adapter",
      role: "Boundary so browser/WASM/native/VR/AR/cloud can all implement the same contract.",
      frozen: true,
    },
    {
      id: 9,
      name: "World Node",
      role: "Deployable multiplayer runtime instance of a Build. Host is an implementation detail.",
      frozen: true,
    },
    {
      id: 10,
      name: "World Service",
      role: "Platform-provided OS services: Multiplayer, Streaming, Persistence, Voice, Ads, Identity... Packages consume them through Contracts — never reinvent them.",
      frozen: true,
    },
  ],
  pipelines: [
    {
      name: "Generation (reuse-first)",
      stages: [
        "Natural Language",
        "World Specification",
        "Package Decomposition",
        "Registry Search",
        "Reuse Existing / Generate Missing",
        "User's LLM (only for missing)",
        "Certified Packages",
        "Composition",
        "World Build",
        "World Node",
        "Living World (multiplayer + streaming + persistence)",
      ],
    },
    {
      name: "Multimodal",
      stages: [
        "Photo / Video / Audio / Scan",
        "Perception → World Specification",
        "…same reuse-first pipeline…",
      ],
    },
  ],
  laws: [
    "A World Project defines what is desired; the PlayLiquid OS determines how that desire can become an operational world.",
    "PlayLiquid is responsible for making packages operational; creators are responsible only for specifying the behavior and implementation of their packages.",
    "If a capability is fundamental to operating a virtual world, it belongs in the PlayLiquid OS substrate rather than in an individual package. (Multiplayer? OS. Streaming? OS. Replication? OS. Identity? OS. Ads? OS service. Payments? OS service. Capability enforcement? Kernel. Spatial composition? OS contract. Hosting? World Node. World-specific behavior? Package. World-specific content? Package. New sensory technology? Runtime Adapter / World Service extension. LLM? Implementation backend chosen by the user.)",
    "No future feature may introduce a fundamental object that bypasses Package, Specification, Contract, Entity, World Project, World Build, Kernel, Runtime Adapter, World Node, or World Service.",
    "The user's LLM implements PACKAGES against OS contracts. It NEVER implements OS substrate (multiplayer, networking, replication, streaming, persistence, capability enforcement, platform services). PlayLiquid knows nothing about which LLM is active — it knows only the LLMProviderAdapter contract.",
    "No future feature should require PlayLiquid to own the user's implementation model, LLM, or hosting infrastructure.",
    "A package must remain reusable across worlds. Worlds layer capability policies on top — they do not modify packages. (Superman can fly in 500 worlds and be grounded in 501 without 501 implementations.)",
    "A substrate contract existing is not the same as a substrate implementation existing. Each OS guarantee is honestly labeled: contract-only, simulator, partial, or production.",
  ],
  // The critical OS-substrate-vs-LLM-implementation distinction
  substrate: {
    osProvides: [
      "Specification system",
      "Package Registry",
      "Dependency resolution",
      "Composition",
      "World builds",
      "Entity lifecycle",
      "Scheduler",
      "Event bus",
      "Networking",
      "Multiplayer / Replication",
      "Spatial partitioning",
      "Streaming",
      "Persistence",
      "Capability enforcement (multi-layer)",
      "Asset delivery",
      "World hosting (World Nodes)",
      "Observability",
      "Moderation hooks",
      "Platform services (Identity, Voice, Ads, Economy...)",
    ],
    llmImplements: [
      "Castles, houses, roads, trees",
      "Avatars, creatures, NPCs, vehicles",
      "Weather systems, economies, quest systems",
      "Museums, schools, Mars rovers, spaceships",
      "World-specific visual style, architecture, materials",
      "Domain logic that consumes OS contracts",
    ],
  },
  kernelServices: [
    { name: "Scheduler", contract: "kernel.scheduler", role: "Advances simulation ticks; orders entity updates." },
    { name: "Event Bus", contract: "kernel.events", role: "Pub/sub for entity and system events." },
    { name: "Entity Runtime", contract: "kernel.entities", role: "Spawns, updates, despawns entities from packages." },
    { name: "Capability System", contract: "kernel.capabilities", role: "Multi-layer negotiation: entity × world × zone × experience = effective." },
    { name: "Networking", contract: "kernel.networking", role: "Transport abstraction. Packages never implement transport." },
    { name: "Replication", contract: "kernel.replication", role: "Authoritative state → interested clients. Automatic for all packages." },
    { name: "Session Management", contract: "kernel.sessions", role: "Player connections, presence, reconnect." },
    { name: "Spatial Authority", contract: "kernel.spatial", role: "Cells, regions, interest management, streaming partitions." },
    { name: "Persistence", contract: "kernel.persistence", role: "World/entity state survives restart. Adapter-based (Postgres/IPFS/local)." },
    { name: "Streaming", contract: "kernel.streaming", role: "Loads/unloads spatial cells based on player interest. Packages declare bounds + LOD." },
  ],
  extensionTable: [
    { capability: "Multiplayer", extensionPoint: "Kernel / Replication + Sessions (OS substrate, NOT LLM)" },
    { capability: "Dedicated servers", extensionPoint: "World Node" },
    { capability: "P2P worlds", extensionPoint: "World Node" },
    { capability: "Streaming", extensionPoint: "Kernel / Spatial Authority (OS substrate)" },
    { capability: "Persistence", extensionPoint: "Kernel / Persistence Adapter (OS substrate)" },
    { capability: "Avatars", extensionPoint: "Package + Entity + Capability Policy" },
    { capability: "Capability restrictions", extensionPoint: "Kernel / Multi-layer Capability Negotiation" },
    { capability: "Physics", extensionPoint: "Runtime Adapter / Package" },
    { capability: "Rendering", extensionPoint: "Runtime Adapter" },
    { capability: "VR / AR", extensionPoint: "Runtime Adapter" },
    { capability: "Audio", extensionPoint: "Package + Runtime Service" },
    { capability: "Voice", extensionPoint: "World Service (OS substrate)" },
    { capability: "Smell / Haptics", extensionPoint: "Sensory Package + Runtime Adapter" },
    { capability: "Advertising", extensionPoint: "World Service (OS substrate) — never LLM-generated" },
    { capability: "Economy", extensionPoint: "World Service (OS substrate)" },
    { capability: "AI agents", extensionPoint: "Entity + Knowledge/AI Package" },
    { capability: "Real-world reconstruction", extensionPoint: "Multimodal → Specification" },
    { capability: "New LLM providers", extensionPoint: "Provider Adapter" },
    { capability: "New hosting providers", extensionPoint: "World Node Adapter" },
    { capability: "New execution technology", extensionPoint: "Runtime Adapter" },
  ],
  // Stage 1 — the 11 universal substrate guarantees PlayLiquid provides.
  // A package declares it needs these; the OS supplies them. The LLM never implements them.
  // Each guarantee is honestly labeled with its implementation status:
  //   contract-only = the contract is frozen, no implementation yet
  //   simulator     = a simulator/prototype implementation exists
  //   partial       = some real implementation exists, not production-ready
  //   production    = production-ready
  substrateGuarantees: [
    { name: "Multiplayer", contract: "multiplayer.session", guarantee: "Players connect, see each other, share state. Packages never implement transport or replication.", implementationStatus: "contract-only", note: "No real client sessions, transport, or replication yet. Kernel is a single-process simulator." },
    { name: "Replication", contract: "multiplayer.replication", guarantee: "Authoritative state → interested clients. Automatic for every entity spawned from a package.", implementationStatus: "contract-only", note: "State is written to PostgreSQL but not replicated to clients." },
    { name: "Identity", contract: "identity.player", guarantee: "Player identity, sessions, capability tokens. Packages consume identity; they don't build auth.", implementationStatus: "partial", note: "NextAuth credentials provider exists for the console; not yet a world-player identity system." },
    { name: "Persistence", contract: "kernel.persistence", guarantee: "World and entity state survives restart. Adapter-based (Postgres/IPFS/local).", implementationStatus: "simulator", note: "State persists in Neon Postgres; no adapter abstraction yet." },
    { name: "Streaming", contract: "kernel.streaming", guarantee: "Loads/unloads spatial cells based on player interest. Packages declare bounds + LOD; the OS handles the rest.", implementationStatus: "contract-only", note: "No spatial partitioning, cell loading, or interest management yet." },
    { name: "Spatial Services", contract: "kernel.spatial", guarantee: "Cells, regions, interest management, handoff between World Nodes.", implementationStatus: "contract-only", note: "SpatialSlot model exists with formal contracts; no runtime spatial authority." },
    { name: "Capability Enforcement", contract: "kernel.capabilities", guarantee: "Multi-layer negotiation: entity × world × zone × experience = effective. The Kernel enforces, not the package.", implementationStatus: "partial", note: "Negotiation engine works; Kernel gate now enforces (no direct path to execution)." },
    { name: "Economy", contract: "economy.wallet", guarantee: "Currency, transactions, wallets. Platform service; worlds opt in.", implementationStatus: "contract-only", note: "No wallet, currency, or transaction implementation." },
    { name: "Advertising", contract: "ads.surfaces", guarantee: "Ad placements, auctions, billing, frequency caps. Worlds declare ad policy; the OS handles the machinery.", implementationStatus: "contract-only", note: "No ad network adapter, auction, or billing." },
    { name: "Voice", contract: "voice.spatial", guarantee: "Spatial voice chat. Platform-provided; worlds opt in.", implementationStatus: "contract-only", note: "No voice transport." },
    { name: "Discovery", contract: "discovery.worlds", guarantee: "Worlds are discoverable, addressable, linkable. Hosting is an implementation detail.", implementationStatus: "partial", note: "World projects are listable via API; no federation or node discovery." },
  ],
  // The operational test — a decision rule for "is this OS or Package?"
  operationalTest: {
    rule: "If a capability is fundamental to operating a virtual world, it belongs in the PlayLiquid OS substrate rather than in an individual package.",
    examples: [
      { capability: "Multiplayer", belongs: "OS", reason: "Fundamental to operating a multiplayer world." },
      { capability: "Streaming", belongs: "OS", reason: "Fundamental to operating a large world." },
      { capability: "Replication", belongs: "OS", reason: "Fundamental to multiplayer state." },
      { capability: "Identity", belongs: "OS", reason: "Fundamental to player presence." },
      { capability: "Ads", belongs: "OS Service", reason: "Platform-level capability consumed via contract." },
      { capability: "Payments", belongs: "OS Service", reason: "Platform-level capability consumed via contract." },
      { capability: "Capability enforcement", belongs: "Kernel", reason: "The Kernel enforces policies; packages declare." },
      { capability: "Spatial composition", belongs: "OS Contract", reason: "The Composer resolves spatial attachment." },
      { capability: "Hosting", belongs: "World Node", reason: "A World Node hosts a Build; host is an implementation detail." },
      { capability: "World-specific behavior", belongs: "Package", reason: "Domain logic — the LLM implements this." },
      { capability: "World-specific content", belongs: "Package", reason: "Castles, avatars, weather — the LLM implements this." },
      { capability: "New sensory technology", belongs: "Runtime Adapter / World Service", reason: "Extension point, not a new primitive." },
      { capability: "LLM", belongs: "Implementation backend chosen by the user", reason: "PlayLiquid doesn't own the LLM; it owns the boundary." },
    ],
  },
  roadmap: [
    { stage: "0", name: "Frozen OS Primitives", status: "done", detail: "10 primitives frozen: Package, Specification, Contract, Entity, World Project, World Build, Kernel, Runtime Adapter, World Node, World Service." },
    { stage: "1", name: "Universal Substrate", status: "in-progress", detail: "Platform guarantees: multiplayer, replication, identity, persistence, streaming, spatial, capability enforcement, economy, advertising, voice, discovery. The LLM never implements these." },
    { stage: "2", name: "Package Resolution", status: "in-progress", detail: "Specification → dependency graph → registry search → semantic + theme/style matching → reuse → generate only missing." },
    { stage: "3", name: "World Projects at Scale", status: "in-progress", detail: "Branches, contributions, PRs, review, merge, versioning, spatial contracts, ownership, provenance, build history." },
    { stage: "4", name: "Distributed World Runtime", status: "partial", detail: "World Nodes provide multiplayer, streaming, replication, persistence, server handoff, presence, world services." },
    { stage: "5", name: "Multimodal World Compiler", status: "planned", detail: "Text, image, video, audio, 3D scans, documents → canonical specification → reuse-first pipeline." },
    { stage: "6", name: "Marketplace + World Economy", status: "planned", detail: "Packages tradable: licensing, purchases, subscriptions, royalties, advertising, creator revenue." },
    { stage: "7", name: "Sensory Runtime", status: "planned", detail: "Sight, sound, touch, smell, proprioception — sensory interfaces as Runtime Adapter / World Service extensions." },
  ],
};
